stages:
  load_mlflow_models:
    cmd: MODELS_DIR=../models DVC_DIR=. python3 ../pipeline/stages/load_models.py
    deps:
    - ../models/sales_prediction/models/
    - ../models/quantity_prediction/models/
    - ../models/computer_vision_2/
    outs:
    - data/
  evaluate_models:
    cmd: DVC_DIR=. python3 ../pipeline/stages/evaluate.py
    deps:
    - data/
    metrics:
    - metrics/evaluation.json:
        cache: false
