FROM python:3.11-slim

WORKDIR /app

COPY docker/requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY . .

# Explicitly add /app to Python module search path
ENV PYTHONPATH=/app

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]